definition
defineTraits
	tWithDerivedTableReference := builder newTraitNamed: #TWithDerivedTableReference.
	tWithColumnReference := builder newTraitNamed: #TWithColumnReference.
	tWithTableReference := builder newTraitNamed: #TWithTableReference.
	tWithViewReference := builder newTraitNamed: #TWithViewReference.
	tWithAlias := builder newTraitNamed: #TWithAlias.
	tWithCursor := builder newTraitNamed: #TWithCursor.
	tWithCursorReference := builder newTraitNamed: #TWithCursorReference.
	tReferencesGroupReference := builder newTraitNamed: #TReferencesGroupReference.
	tWithReferencesGroupReference := builder newTraitNamed: #TWithReferencesGroupReference